### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by a3020** [JDilleen/datatables-bulma#3]
Fyi, the example in the README doesn't work (anymore):

https://camo.githubusercontent.com/9b750f46a1528bc5f2a65698f4ca195b85d94b7d/68747470733a2f2f6a64696c6c65656e2e6d652f696e636c756465732f696d672f62756c6d612e706e67

**Comment by JDilleen** [comment]
@a3020 - Thanks for the heads up :)
